export const GET_POSTS = 'GET_POSTS'
export const GET_IMAGES = 'GET_IMAGES'
export const POST_DETAILS = 'POST_DETAILS'
export const SET_LOADER = 'SET_LOADER'
export const SET_PAGE = 'SET_PAGE'
export const SET_MAX_PAGE_VALUE = 'SET_MAX_PAGE_VALUE'